apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.monitorLoki.pvcName }}
  labels:
    app: {{ .Values.monitorLoki.name }}
  {{- with .Values.monitorLoki.pvcLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.monitorLoki.storage }}