{{- if .Values.backendScheduler.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backendScheduler.name }}
  labels:
    app: {{ .Values.backendScheduler.name }}
  annotations:
    {{- toYaml .Values.backendCommon.annotations | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.backendScheduler.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.backendScheduler.name }}
    spec:
{{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
{{- end }}    
      affinity: 
        {{- toYaml .Values.backendScheduler.affinity | nindent 8 }}
      containers:
      - name: {{ .Values.backendScheduler.name }}      
        image: {{ .Values.backendCommon.image }}:{{ .Chart.AppVersion }}
        command: 
        - sh
        - '-c'
        - >
          until pnpm check:db > /dev/null 2>&1; 
          do echo waiting for db ...; sleep 10; done && 
          echo db is ready &&        
          node dist/apps/backend/main.js
        env:
        - name: MPROVE_RELEASE_TAG
          value: {{ .Chart.AppVersion }}
        - name: BACKEND_IS_SCHEDULER
          value: 'TRUE'      
        - name: CLI_DRIZZLE_POSTGRES_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backendCommon.envsSecretName }}
              key: BACKEND_POSTGRES_DATABASE_URL  
        envFrom:
        - secretRef:
            name: {{ .Values.backendCommon.envsSecretName }}    
        volumeMounts:
        - name: scheduler-secrets-volume
          mountPath: /usr/src/app/secrets
      volumes:
      - name: scheduler-secrets-volume
        secret:
          secretName: {{ .Values.backendCommon.extraSecretName }}
          items:
          - key: demoProjectBigqueryCredentials
            path: demo-project-bigquery-credentials.json
          - key: demoProjectGoogleApiCredentials
            path: demo-project-google-api-credentials.json
          - key: demoProjectRemotePrivateKeyEncrypted
            path: demo-project-remote-private-key-encrypted.pem
          - key: demoProjectRemotePublicKey
            path: demo-project-remote-public-key.pem
{{- end }}

