apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.backend.name }}
  labels:
    app:  {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app:  {{ .Values.backend.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  {{ .Values.backend.name }}
    spec:
      containers:
      - name: {{ .Values.backend.name }}
        image: {{ .Values.backendCommon.image }}:{{ .Chart.AppVersion }}
        command: 
        - sh
        - '-c'
        - >
          until wget http://$BACKEND_RABBIT_USER:$BACKEND_RABBIT_PASS@$BACKEND_RABBIT_HOST:15672/api/aliveness-test/%2F > /dev/null 2>&1; 
          do echo waiting for rabbit ...; sleep 10; done && 
          echo rabbit is ready &&
          until yarn typeorm query "SELECT 1" > /dev/null 2>&1; 
          do echo waiting for db ...; sleep 10; done && 
          echo db is ready &&        
          node dist/apps/backend/main.js
        env:
        - name: TYPEORM_CONNECTION
          value: mysql
        - name: TYPEORM_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backendCommon.envsSecretName }}
              key: BACKEND_MYSQL_HOST
        - name: TYPEORM_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backendCommon.envsSecretName }}
              key: BACKEND_MYSQL_USERNAME
        - name: TYPEORM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backendCommon.envsSecretName }}
              key: BACKEND_MYSQL_PASSWORD        
        - name: BACKEND_IS_SCHEDULER
          value: 'FALSE'
        envFrom:
        - secretRef:
            name: {{ .Values.backendCommon.envsSecretName }}    
        ports:
        - containerPort: 3000
          name: backend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    name: {{ .Values.backend.name }} 