apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backendScheduler.name }}
  labels:
    app: {{ .Values.backendScheduler.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.backendScheduler.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.backendScheduler.name }}
    spec:
      containers:
      - name: {{ .Values.backendScheduler.name }}
        image: {{ .Values.backendScheduler.image }}:{{ .Chart.AppVersion }}
        command: ['yarn']
        args: ['serve:backend']
        env:
        - name: BACKEND_IS_SCHEDULER
          value: 'TRUE'           
        envFrom:
        - secretRef:
            name: {{ .Values.backendCommon.envsSecretName }}    
        volumeMounts:
        - name: scheduler-secrets-volume
          mountPath: /usr/src/app/secrets
      volumes:
      - name: scheduler-secrets-volume
        secret:
          secretName: {{ .Values.backendCommon.bigquerySecretName }}
          items:
          - key: content
            path: bigquery-test.json

