apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    name: {{ .Values.backend.name }} 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.backend.name }}
  labels:
    app:  {{ .Values.backend.name }}
  annotations:
    {{- toYaml .Values.backendCommon.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app:  {{ .Values.backend.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  {{ .Values.backend.name }}
    spec:
{{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
{{- end }}    
      affinity: 
        {{- toYaml .Values.backend.affinity | nindent 8 }}
      containers:
      - name: {{ .Values.backend.name }}
        image: {{ .Values.backendCommon.image }}:{{ .Chart.AppVersion }}
        command: 
        - sh
        - '-c'
        - >
          until pnpm check:db > /dev/null 2>&1; 
          do echo waiting for db ...; sleep 10; done && 
          echo db is ready &&        
          node --enable-source-maps apps/backend/dist/main.js
        env:
        - name: MPROVE_RELEASE_TAG
          value: {{ .Chart.AppVersion }}
        - name: BACKEND_IS_SCHEDULER
          value: 'FALSE'
        - name: CLI_DRIZZLE_POSTGRES_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backendCommon.envsSecretName }}
              key: BACKEND_POSTGRES_DATABASE_URL
        envFrom:
        - secretRef:
            name: {{ .Values.backendCommon.envsSecretName }}    
        ports:
        - containerPort: 3000
          name: backend

