apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.blockmlMainWorker.name }}
  labels:
    app: {{ .Values.blockmlMainWorker.name }}
spec:
  replicas: {{ .Values.blockmlMainWorker.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.blockmlMainWorker.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.blockmlMainWorker.name }}
    spec:
      containers:
      - name: {{ .Values.blockmlMainWorker.name }}
        image: {{ .Values.blockmlCommon.image }}:{{ .Chart.AppVersion }}
        command: 
        - sh
        - '-c'
        - >
          until wget http://$BLOCKML_RABBIT_USER:$BLOCKML_RABBIT_PASS@$BLOCKML_RABBIT_HOST:15672/api/aliveness-test/%2F > /dev/null 2>&1; 
          do echo waiting for rabbit ...; sleep 10; done && 
          echo rabbit is ready &&        
          node dist/apps/blockml/main.js
        env:        
        - name: BLOCKML_IS_MAIN
          value: 'TRUE'        
        - name: BLOCKML_IS_WORKER
          value: 'TRUE'        
        - name: BLOCKML_IS_SINGLE
          value: 'FALSE'          
        envFrom:
        - secretRef:
            name: {{ .Values.blockmlCommon.envsSecretName }}