apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.blockmlSingle.name }}
  labels:
    app: {{ .Values.blockmlSingle.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.blockmlSingle.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.blockmlSingle.name }}
    spec:
      containers:
      - name: {{ .Values.blockmlSingle.name }}
        image: {{ .Values.blockmlSingle.image }}:{{ .Chart.AppVersion }}
        command: ['yarn']
        args: ['serve:blockml']        
        envFrom:
        - secretRef:
            name: {{ .Values.blockmlSingle.envsSecretName }}