apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.disk.name }}
  labels:
    app: {{ .Values.disk.name }}
spec:
  serviceName: {{ .Values.disk.name }}
  selector:
    matchLabels:
      app: {{ .Values.disk.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.disk.name }}
    spec:
      containers:
      - name: {{ .Values.disk.name }}
        image: {{ .Values.disk.image }}:{{ .Chart.AppVersion }}
        command: 
        - sh
        - '-c'
        - >
          until wget http://$DISK_RABBIT_USER:$DISK_RABBIT_PASS@$DISK_RABBIT_HOST:15672/api/aliveness-test/%2F > /dev/null 2>&1; 
          do echo waiting for rabbit ...; sleep 10; done && 
          echo rabbit is ready &&        
          node dist/apps/disk/main.js        
        envFrom:
        - secretRef:
            name: {{ .Values.disk.envsSecretName }}    
        volumeMounts:
        - name: disk-persistent-storage
          mountPath: /root/mprove_data/organizations
      volumes:
      - name: disk-persistent-storage
        persistentVolumeClaim:
          claimName: disk-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-pvc
  labels:
    app: {{ .Values.disk.name }}
  {{- with .Values.disk.pvcLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.disk.storage }}

