apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.dwhClickhouse.name }}
  labels:
    app: {{ .Values.dwhClickhouse.name }}
spec:
  serviceName: {{ .Values.dwhClickhouse.name }}
  selector:
    matchLabels:
      app: {{ .Values.dwhClickhouse.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dwhClickhouse.name }}
    spec:
      containers:
      - name: {{ .Values.dwhClickhouse.name }}
        image: {{ .Values.dwhClickhouse.image }}:{{ .Chart.AppVersion }}
        envFrom:
        - secretRef:
            name: {{ .Values.dwhClickhouse.envsSecretName }}          
        ports:
        - containerPort: 8123
          name: clickhouse-main
        # - containerPort: 9000
        #   name: clickhouse-clt
        volumeMounts:
        - name: {{ .Values.dwhClickhouse.name }}-persistent-storage
          mountPath: /var/lib/clickhouse        
        - name: {{ .Values.dwhClickhouse.name }}-logs-persistent-storage
          mountPath: /var/lib/clickhouse-server
      volumes:
      - name: {{ .Values.dwhClickhouse.name }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.dwhClickhouse.name }}-pvc
      - name: {{ .Values.dwhClickhouse.name }}-logs-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.dwhClickhouse.name }}-logs-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dwhClickhouse.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dwhClickhouse.storage }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dwhClickhouse.name }}-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dwhClickhouse.storageLogs }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dwhClickhouse.name }}
  labels:
    app: {{ .Values.dwhClickhouse.name }}
spec:
  selector:
    app: {{ .Values.dwhClickhouse.name }}
  type: NodePort
  ports:
  - port: 8123
    targetPort: 8123
    name: clickhouse-main  
  # - port: 9000
  #   targetPort: 9000
  #   name: clickhouse-clt