{{- if .Values.dwhPostgres.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.dwhPostgres.name }}
  labels:
    app: {{ .Values.dwhPostgres.name }}
spec:
  serviceName: {{ .Values.dwhPostgres.name }}
  selector:
    matchLabels:
      app: {{ .Values.dwhPostgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dwhPostgres.name }}
    spec:
      containers:
      - name: {{ .Values.dwhPostgres.name }}
        image: {{ .Values.dwhPostgres.image }}:{{ .Chart.AppVersion }}
        envFrom:
        - secretRef:
            name: {{ .Values.dwhPostgres.envsSecretName }} 
        ports:
        - containerPort: 5432
          name: {{ .Values.dwhPostgres.name }}
        volumeMounts:
        - name: {{ .Values.dwhPostgres.name }}-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: {{ .Values.dwhPostgres.name }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.dwhPostgres.name }}-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dwhPostgres.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dwhPostgres.storage }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dwhPostgres.name }}
  labels:
    app: {{ .Values.dwhPostgres.name }}
spec:
  selector:
    app: {{ .Values.dwhPostgres.name }}
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
{{- end }}    