ingress:
  enabled: true
  host: real-host.example.com
  acmeEmail: real-email@example.com

db:
  envs:
    MYSQL_ROOT_PASSWORD: replaceWith32CharString

rabbit:
  envs:
    RABBITMQ_DEFAULT_PASS: replaceWith32CharString
    RABBITMQ_ERLANG_COOKIE: replaceWith32CharString

front:
  replicas: 1

disk:
  envs:
    DISK_RABBIT_PASS: replaceWith32CharString

blockmlMainWorker:
  replicas: 1

blockmlCommon:
  envs:
    BLOCKML_RABBIT_PASS: replaceWith32CharString

backend:
  replicas: 1

backendCommon:
  envs:
    BACKEND_MYSQL_PASSWORD: replaceWith32CharString
    BACKEND_RABBIT_PASS: replaceWith32CharString
    BACKEND_JWT_SECRET: replaceWith32CharString
    BACKEND_SPECIAL_KEY: replaceWith32CharString
    BACKEND_FIRST_USER_EMAIL: real-email@example.com
    BACKEND_FIRST_USER_PASSWORD: userpass
    BACKEND_FIRST_ORG_ID:
    BACKEND_FIRST_PROJECT_ID:
    BACKEND_HOST_URL: https://real-host.example.com
    BACKEND_SEND_EMAIL_FROM_NAME: My Company Name
    BACKEND_SEND_EMAIL_FROM_ADDRESS: no-reply@example.com
    BACKEND_SMTP_HOST: real-smtp.example.com
    BACKEND_SMTP_AUTH_USER: realSmtpUser
    BACKEND_SMTP_AUTH_PASSWORD: realSmtpPassword

dwhPostgres:
  enabled: false

dwhClickhouse:
  enabled: false