imagePullSecrets:
  enabled: false
  name: secretname

docs:
  createEnvsSecret: true
  name: docs
  replicas: 1
  affinity: {}
  image: ghcr.io/mprove-io/mprove-docs
  envsSecretName: secret-docs
  envs:
    NODE_ENV: production
    DOCS_ORIGIN: https://docs.mprove.io
    OPENAPI_SERVER_URL: http://app.mprove.io
    OPENAPI_SCHEMA_URL: http://app.mprove.io/api/openapi.json