apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.maintenance.name }}
  name: {{ .Values.maintenance.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.maintenance.name }}
  ports:
  - name: maintenance
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.maintenance.name }}
  name: {{ .Values.maintenance.name }}
spec:
  replicas: {{ .Values.maintenance.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.maintenance.name }}
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: {{ .Values.maintenance.name }}
    spec:
{{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
{{- end }}    
      affinity: 
        {{- toYaml .Values.maintenance.affinity | nindent 8 }}
      containers:
      - name: {{ .Values.maintenance.name }}
        image: {{ .Values.maintenance.image }}:{{ .Values.maintenance.tag }}
        ports:
        - containerPort: 80
          name: maintenance
          
