{{- if .Values.disk.createEnvsSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.disk.envsSecretName }}
type: Opaque
data:
  {{- range $key, $val := .Values.disk.envs }}
  "{{ $key }}": "{{ $val }}"
  {{- end }}
{{- end }}