{{- if .Values.backendCommon.createEnvsSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backendCommon.envsSecretName }}
type: Opaque
data:
  {{- range $key, $val := .Values.backendCommon.envs }}
  "{{ $key }}": "{{ $val | toString | b64enc }}"
  {{- end }}
{{- end }}