{{- if .Values.dwhClickhouse.createEnvsSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dwhClickhouse.envsSecretName }}
type: Opaque
data:
  {{- range $key, $val := .Values.dwhClickhouse.envs }}
  "{{ $key }}": "{{ $val }}"
  {{- end }}
{{- end }}