{{- if .Values.backendCommon.createSecretFilesSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backendCommon.secretFilesSecretName }}
type: Opaque
data:
  contentBigquery: {{ .Values.backendCommon.firstProjectBigqueryCredentials | toString | b64enc }}
  contentRemotePrivateKey: {{ .Values.backendCommon.firstProjectRemotePrivateKey | b64enc }}
  contentRemotePublicKey: {{ .Values.backendCommon.firstProjectRemotePublicKey | b64enc }}
{{- end }}  