{{- if .Values.backendCommon.createExtraSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backendCommon.extraSecretName }}
type: Opaque
data:
  demoProjectBigqueryCredentials: {{ .Values.backendCommon.extra.demoProjectBigqueryCredentials | toString | b64enc }}
  demoProjectGoogleApiCredentials: {{ .Values.backendCommon.extra.demoProjectGoogleApiCredentials | b64enc }}
  demoProjectRemotePrivateKeyEncrypted: {{ .Values.backendCommon.extra.demoProjectRemotePrivateKeyEncrypted | b64enc }}
  demoProjectRemotePublicKey: {{ .Values.backendCommon.extra.demoProjectRemotePublicKey | b64enc }}
{{- end }}  