{{- if .Values.calcPostgres.createInitSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.calcPostgres.initSecretName }}
type: Opaque
stringData:
  script: |-
    #!/bin/bash
    set -euo pipefail

    psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
        DO \$\$
        BEGIN
            CREATE ROLE "{{ .Values.calcPostgres.envs.CALC_USER }}"
                WITH LOGIN
                PASSWORD '{{ .Values.calcPostgres.envs.CALC_PASSWORD }}'
                NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
        EXCEPTION WHEN duplicate_object THEN
            ALTER ROLE "{{ .Values.calcPostgres.envs.CALC_USER }}"
                WITH LOGIN
                PASSWORD '{{ .Values.calcPostgres.envs.CALC_PASSWORD }}';
        END
        \$\$;

        GRANT CONNECT ON DATABASE postgres TO "{{ .Values.calcPostgres.envs.CALC_USER }}";

        REVOKE ALL ON SCHEMA public FROM "{{ .Values.calcPostgres.envs.CALC_USER }}";
        REVOKE ALL ON SCHEMA public FROM PUBLIC;

        REVOKE EXECUTE ON FUNCTION pg_catalog.pg_terminate_backend FROM "{{ .Values.calcPostgres.envs.CALC_USER }}";
        REVOKE EXECUTE ON FUNCTION pg_catalog.pg_cancel_backend FROM "{{ .Values.calcPostgres.envs.CALC_USER }}";
        REVOKE EXECUTE ON FUNCTION pg_catalog.pg_stat_get_activity FROM "{{ .Values.calcPostgres.envs.CALC_USER }}";
    EOSQL

    echo "User '{{ .Values.calcPostgres.envs.CALC_USER }}' created/updated."
{{- end }}